services:
    sokil.message_bus.type_locator:
        class: Sokil\MessageBusBundle\Service\TypeLocator
        arguments:
            - [] # Map of stub class names to types injected in extension
            - [] # Map of message class names to types injected in extension
    
    sokil.message_bus.middleware.amqp_message_routing_key_by_type:
        class: Sokil\MessageBusBundle\Middleware\AmqpMessageRoutingKeyByTypeMiddleware
        arguments:
            - "@sokil.message_bus.type_locator"
            - "{messageType}" # May be replaced by configuration

    sokil.message_bus.transport.dummy.transport_factory:
        class: Sokil\MessageBusBundle\Transport\Dummy\DummyMessengerTransportFactory
        tags: [messenger.transport_factory]
        arguments:
            - null # Must be defined in MessageBusExtension
