services:
    message_bus.type_locator:
        class: Sokil\MessageBus\Service\TypeLocator
        arguments:
            - [] # Map of class names to types injected in extension
            - [] # Map of class names to types injected in extension
    
    message_bus.middleware.amqp_message_routing_key_by_type:
        class: Sokil\MessageBus\Middleware\AmqpMessageRoutingKeyByTypeMiddleware
        arguments:
            - "@message_bus.type_locator"
            - "{messageType}" # May be replaced by configuration

    message_bus.transport.dummy.transport_factory:
        class: Sokil\MessageBus\Transport\Dummy\DummyMessengerTransportFactory
        tags: [messenger.transport_factory]
        arguments:
            - null # Must be defined in KafkaClientExtension
